### ISSUE TITLE
Introduce SQL Database

### ISSUE THREAD

**Issue by paddybun** [paddybun/document.lib.api#2]
# ⚙️ Introduce SQL

Currently only CosmosDB is supported, due to (my) limitations on working with NoSQL databases, a SQL database should be introduced and supported.

## Tasks

- [x] Create Service - Repository pattern to support both databases
- [x] Use entity framework to handle SQL interaction (no SQL strings in code)
- [x] Refactor existing services
